algoritmo "Creuza01"
// Função : Creuza vai fazer aniversário
// Autor : Rafael Corrêa
// Data : 03/05/2022
// Seção de Declarações 
var
   ano_atual, ano_nasc, idade: Inteiro
inicio
// Seção de Comandos
   Escreva("Em que ano nós estamos? ")
   Leia(ano_atual)
   Escreva("Em que ano eu nasci? ")
   Leia(ano_nasc)
   idade <- ano_atual - ano_nasc
   Escreva("Minha idade será", idade)
fimalgoritmo
