algoritmo "FazSomaProcedimento"
// Função : Fazer soma a partir de um Procedimento
// Autor : Rafael Corrêa
// Data : 05/05/2022
// Seção de Declarações 
var
   X, Y: Inteiro
   
   Procedimento Soma(A, B: Inteiro)
   Inicio
         EscrevaL("Recebi o valor", A)
         EscrevaL("Recebi o valor", B)
         EscrevaL("A soma entre os dois é", A + B)
   FimProcedimento
inicio
// Seção de Comandos
   X <- 5
   Y <- 3
   Soma(X, Y)
fimalgoritmo
